name: Build and test

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven   
        
    - name: Install Google Chrome
      run: |
        $chrome_installer = "C:\chrome_installer.exe"
        Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/standalonesetup64.exe" -OutFile $chrome_installer
        Start-Process -FilePath $chrome_installer -ArgumentList "/silent /install" -Wait
        Remove-Item -Force $chrome_installer
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build with Maven
      run: mvn clean install -e

    - name: Run tests with Maven
      run: mvn test -e

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
